import {
  add,
  addCircleOutline,
  alertCircle,
  bagHandle,
  bagHandleOutline,
  beer,
  bicycle,
  briefcase,
  card,
  cash,
  checkmark,
  checkmarkCircle,
  chevronBack,
  chevronDown,
  chevronForward,
  close,
  cloudOfflineOutline,
  createOutline,
  ellipsisHorizontal,
  eyeOffOutline,
  eyeOutline,
  fastFood,
  flame,
  heart,
  heartOutline,
  home,
  iceCream,
  informationCircle,
  language,
  leaf,
  location,
  logOutOutline,
  notificationsOutline,
  nutrition,
  optionsOutline,
  person,
  personOutline,
  pizza,
  pricetags as priceTags,
  radioButtonOff,
  radioButtonOn,
  receiptOutline,
  remove,
  restaurant,
  restaurantOutline,
  searchOutline,
  shareSocialOutline,
  star,
  starHalf,
  starOutline,
  timeOutline,
  trashOutline,
  water,
} from 'ionicons/icons';

/**
 * Every icon the design system is allowed to use, keyed by a stable name so
 * data and props can reference an icon without importing ionicons.
 * Emoji are never a substitute for an entry here.
 */
export const icons = {
  add,
  addCircleOutline,
  alertCircle,
  bagHandle,
  bagHandleOutline,
  beer,
  bicycle,
  briefcase,
  card,
  cash,
  checkmark,
  checkmarkCircle,
  chevronBack,
  chevronDown,
  chevronForward,
  close,
  cloudOfflineOutline,
  createOutline,
  ellipsisHorizontal,
  eyeOffOutline,
  eyeOutline,
  fastFood,
  flame,
  heart,
  heartOutline,
  home,
  iceCream,
  informationCircle,
  language,
  leaf,
  location,
  logOutOutline,
  notificationsOutline,
  nutrition,
  optionsOutline,
  person,
  personOutline,
  pizza,
  priceTags,
  radioButtonOff,
  radioButtonOn,
  receiptOutline,
  remove,
  restaurant,
  restaurantOutline,
  searchOutline,
  shareSocialOutline,
  star,
  starHalf,
  starOutline,
  timeOutline,
  trashOutline,
  water,
} as const;

export type IconName = keyof typeof icons;

/** Resolves a data-level icon key, falling back to a neutral glyph. */
export const resolveIcon = (name: string): string =>
  icons[name as IconName] ?? icons.ellipsisHorizontal;
